/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SenYul (https://sketchfab.com/senyul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rainbow-morph-animation-18c96b42cf7d433ca72df475cd6ec4d8
Title: Rainbow morph animation
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import CubeModel from  '../models/cube.glb'	
const CubeLogo = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(CubeModel)
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="sketchfabtimeframe">
            <group name="Object_2" scale={0}>
              <group name="frame_99">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Material_98}
                />
              </group>
            </group>
            <group name="Object_5" scale={0}>
              <group name="frame_98">
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Material_97}
                />
              </group>
            </group>
            <group name="Object_8" scale={0}>
              <group name="frame_97">
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Material_96}
                />
              </group>
            </group>
            <group name="Object_11" scale={0}>
              <group name="frame_96">
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Material_95}
                />
              </group>
            </group>
            <group name="Object_14" scale={0}>
              <group name="frame_95">
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Material_94}
                />
              </group>
            </group>
            <group name="Object_17" scale={0}>
              <group name="frame_94">
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.Material_93}
                />
              </group>
            </group>
            <group name="Object_20" scale={0}>
              <group name="frame_93">
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Material_92}
                />
              </group>
            </group>
            <group name="Object_23" scale={0}>
              <group name="frame_92">
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Material_91}
                />
              </group>
            </group>
            <group name="Object_26" scale={0}>
              <group name="frame_91">
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.Material_90}
                />
              </group>
            </group>
            <group name="Object_29" scale={0}>
              <group name="frame_90">
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.Material_89}
                />
              </group>
            </group>
            <group name="Object_32" scale={0}>
              <group name="frame_89">
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.Material_88}
                />
              </group>
            </group>
            <group name="Object_35" scale={0}>
              <group name="frame_88">
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.Material_87}
                />
              </group>
            </group>
            <group name="Object_38" scale={0}>
              <group name="frame_87">
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.Material_86}
                />
              </group>
            </group>
            <group name="Object_41" scale={0}>
              <group name="frame_86">
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.Material_85}
                />
              </group>
            </group>
            <group name="Object_44" scale={0}>
              <group name="frame_85">
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Material_84}
                />
              </group>
            </group>
            <group name="Object_47" scale={0}>
              <group name="frame_84">
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.Material_83}
                />
              </group>
            </group>
            <group name="Object_50" scale={0}>
              <group name="frame_83">
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.Material_82}
                />
              </group>
            </group>
            <group name="Object_53" scale={0}>
              <group name="frame_82">
                <mesh
                  name="Object_55"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={materials.Material_81}
                />
              </group>
            </group>
            <group name="Object_56" scale={0}>
              <group name="frame_81">
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.Material_80}
                />
              </group>
            </group>
            <group name="Object_59" scale={0}>
              <group name="frame_80">
                <mesh
                  name="Object_61"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials.Material_79}
                />
              </group>
            </group>
            <group name="Object_62" scale={0}>
              <group name="frame_79">
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.Material_78}
                />
              </group>
            </group>
            <group name="Object_65" scale={0}>
              <group name="frame_78">
                <mesh
                  name="Object_67"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials.Material_77}
                />
              </group>
            </group>
            <group name="Object_68" scale={0}>
              <group name="frame_77">
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.Material_76}
                />
              </group>
            </group>
            <group name="Object_71" scale={0}>
              <group name="frame_76">
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials.Material_75}
                />
              </group>
            </group>
            <group name="Object_74" scale={0}>
              <group name="frame_75">
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.Material_74}
                />
              </group>
            </group>
            <group name="Object_77" scale={0}>
              <group name="frame_74">
                <mesh
                  name="Object_79"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials.Material_73}
                />
              </group>
            </group>
            <group name="Object_80" scale={0}>
              <group name="frame_73">
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.Material_72}
                />
              </group>
            </group>
            <group name="Object_83" scale={0}>
              <group name="frame_72">
                <mesh
                  name="Object_85"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials.Material_71}
                />
              </group>
            </group>
            <group name="Object_86" scale={0}>
              <group name="frame_71">
                <mesh
                  name="Object_88"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials.Material_70}
                />
              </group>
            </group>
            <group name="Object_89" scale={0}>
              <group name="frame_70">
                <mesh
                  name="Object_91"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials.Material_69}
                />
              </group>
            </group>
            <group name="Object_92" scale={0}>
              <group name="frame_69">
                <mesh
                  name="Object_94"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Material_68}
                />
              </group>
            </group>
            <group name="Object_95" scale={0}>
              <group name="frame_68">
                <mesh
                  name="Object_97"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_97.geometry}
                  material={materials.Material_67}
                />
              </group>
            </group>
            <group name="Object_98" scale={0}>
              <group name="frame_67">
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.Material_66}
                />
              </group>
            </group>
            <group name="Object_101" scale={0}>
              <group name="frame_66">
                <mesh
                  name="Object_103"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_103.geometry}
                  material={materials.Material_65}
                />
              </group>
            </group>
            <group name="Object_104" scale={0}>
              <group name="frame_65">
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.Material_64}
                />
              </group>
            </group>
            <group name="Object_107" scale={0}>
              <group name="frame_64">
                <mesh
                  name="Object_109"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_109.geometry}
                  material={materials.Material_63}
                />
              </group>
            </group>
            <group name="Object_110" scale={0}>
              <group name="frame_63">
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.Material_62}
                />
              </group>
            </group>
            <group name="Object_113" scale={0}>
              <group name="frame_62">
                <mesh
                  name="Object_115"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials.Material_61}
                />
              </group>
            </group>
            <group name="Object_116" scale={0}>
              <group name="frame_61">
                <mesh
                  name="Object_118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.Material_60}
                />
              </group>
            </group>
            <group name="Object_119" scale={0}>
              <group name="frame_60">
                <mesh
                  name="Object_121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials.Material_59}
                />
              </group>
            </group>
            <group name="Object_122" scale={0}>
              <group name="frame_59">
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials.Material_58}
                />
              </group>
            </group>
            <group name="Object_125" scale={0}>
              <group name="frame_58">
                <mesh
                  name="Object_127"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials.Material_57}
                />
              </group>
            </group>
            <group name="Object_128" scale={0}>
              <group name="frame_57">
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials.Material_56}
                />
              </group>
            </group>
            <group name="Object_131" scale={0}>
              <group name="frame_56">
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials.Material_55}
                />
              </group>
            </group>
            <group name="Object_134" scale={0}>
              <group name="frame_55">
                <mesh
                  name="Object_136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={materials.Material_54}
                />
              </group>
            </group>
            <group name="Object_137" scale={0}>
              <group name="frame_54">
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials.Material_53}
                />
              </group>
            </group>
            <group name="Object_140" scale={0}>
              <group name="frame_53">
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials.Material_52}
                />
              </group>
            </group>
            <group name="Object_143" scale={0}>
              <group name="frame_52">
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials.Material_51}
                />
              </group>
            </group>
            <group name="Object_146" scale={0}>
              <group name="frame_51">
                <mesh
                  name="Object_148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials.Material_50}
                />
              </group>
            </group>
            <group name="Object_149" scale={0}>
              <group name="frame_50">
                <mesh
                  name="Object_151"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials.Material_49}
                />
              </group>
            </group>
            <group name="Object_152" scale={0}>
              <group name="frame_49">
                <mesh
                  name="Object_154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials.Material_48}
                />
              </group>
            </group>
            <group name="Object_155" scale={0}>
              <group name="frame_48">
                <mesh
                  name="Object_157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials.Material_47}
                />
              </group>
            </group>
            <group name="Object_158" scale={0}>
              <group name="frame_47">
                <mesh
                  name="Object_160"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_160.geometry}
                  material={materials.Material_46}
                />
              </group>
            </group>
            <group name="Object_161" scale={0}>
              <group name="frame_46">
                <mesh
                  name="Object_163"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_163.geometry}
                  material={materials.Material_45}
                />
              </group>
            </group>
            <group name="Object_164" scale={0}>
              <group name="frame_45">
                <mesh
                  name="Object_166"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_166.geometry}
                  material={materials.Material_44}
                />
              </group>
            </group>
            <group name="Object_167" scale={0}>
              <group name="frame_44">
                <mesh
                  name="Object_169"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials.Material_43}
                />
              </group>
            </group>
            <group name="Object_170" scale={0}>
              <group name="frame_43">
                <mesh
                  name="Object_172"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_172.geometry}
                  material={materials.Material_42}
                />
              </group>
            </group>
            <group name="Object_173" scale={0}>
              <group name="frame_42">
                <mesh
                  name="Object_175"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_175.geometry}
                  material={materials.Material_41}
                />
              </group>
            </group>
            <group name="Object_176" scale={0}>
              <group name="frame_41">
                <mesh
                  name="Object_178"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_178.geometry}
                  material={materials.Material_40}
                />
              </group>
            </group>
            <group name="Object_179" scale={0}>
              <group name="frame_40">
                <mesh
                  name="Object_181"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_181.geometry}
                  material={materials.Material_39}
                />
              </group>
            </group>
            <group name="Object_182" scale={0}>
              <group name="frame_39">
                <mesh
                  name="Object_184"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_184.geometry}
                  material={materials.Material_38}
                />
              </group>
            </group>
            <group name="Object_185" scale={0}>
              <group name="frame_38">
                <mesh
                  name="Object_187"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_187.geometry}
                  material={materials.Material_37}
                />
              </group>
            </group>
            <group name="Object_188" scale={0}>
              <group name="frame_37">
                <mesh
                  name="Object_190"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_190.geometry}
                  material={materials.Material_36}
                />
              </group>
            </group>
            <group name="Object_191" scale={0}>
              <group name="frame_36">
                <mesh
                  name="Object_193"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_193.geometry}
                  material={materials.Material_35}
                />
              </group>
            </group>
            <group name="Object_194" scale={0}>
              <group name="frame_35">
                <mesh
                  name="Object_196"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_196.geometry}
                  material={materials.Material_34}
                />
              </group>
            </group>
            <group name="Object_197" scale={0}>
              <group name="frame_34">
                <mesh
                  name="Object_199"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_199.geometry}
                  material={materials.Material_33}
                />
              </group>
            </group>
            <group name="Object_200" scale={0}>
              <group name="frame_33">
                <mesh
                  name="Object_202"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_202.geometry}
                  material={materials.Material_32}
                />
              </group>
            </group>
            <group name="Object_203" scale={0}>
              <group name="frame_32">
                <mesh
                  name="Object_205"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_205.geometry}
                  material={materials.Material_31}
                />
              </group>
            </group>
            <group name="Object_206" scale={0}>
              <group name="frame_31">
                <mesh
                  name="Object_208"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_208.geometry}
                  material={materials.Material_30}
                />
              </group>
            </group>
            <group name="Object_209" scale={0}>
              <group name="frame_30">
                <mesh
                  name="Object_211"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_211.geometry}
                  material={materials.Material_29}
                />
              </group>
            </group>
            <group name="Object_212" scale={0}>
              <group name="frame_29">
                <mesh
                  name="Object_214"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials.Material_28}
                />
              </group>
            </group>
            <group name="Object_215" scale={0}>
              <group name="frame_28">
                <mesh
                  name="Object_217"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_217.geometry}
                  material={materials.Material_27}
                />
              </group>
            </group>
            <group name="Object_218" scale={0}>
              <group name="frame_27">
                <mesh
                  name="Object_220"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials.Material_26}
                />
              </group>
            </group>
            <group name="Object_221" scale={0}>
              <group name="frame_26">
                <mesh
                  name="Object_223"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_223.geometry}
                  material={materials.Material_25}
                />
              </group>
            </group>
            <group name="Object_224" scale={0}>
              <group name="frame_25">
                <mesh
                  name="Object_226"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_226.geometry}
                  material={materials.Material_24}
                />
              </group>
            </group>
            <group name="Object_227" scale={0}>
              <group name="frame_24">
                <mesh
                  name="Object_229"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_229.geometry}
                  material={materials.Material_23}
                />
              </group>
            </group>
            <group name="Object_230" scale={0}>
              <group name="frame_23">
                <mesh
                  name="Object_232"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_232.geometry}
                  material={materials.Material_22}
                />
              </group>
            </group>
            <group name="Object_233" scale={0}>
              <group name="frame_22">
                <mesh
                  name="Object_235"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_235.geometry}
                  material={materials.Material_21}
                />
              </group>
            </group>
            <group name="Object_236" scale={0}>
              <group name="frame_21">
                <mesh
                  name="Object_238"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_238.geometry}
                  material={materials.Material_20}
                />
              </group>
            </group>
            <group name="Object_239" scale={0}>
              <group name="frame_20">
                <mesh
                  name="Object_241"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_241.geometry}
                  material={materials.Material_19}
                />
              </group>
            </group>
            <group name="Object_242" scale={0}>
              <group name="frame_19">
                <mesh
                  name="Object_244"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_244.geometry}
                  material={materials.Material_18}
                />
              </group>
            </group>
            <group name="Object_245" scale={0}>
              <group name="frame_18">
                <mesh
                  name="Object_247"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_247.geometry}
                  material={materials.Material_17}
                />
              </group>
            </group>
            <group name="Object_248" scale={0}>
              <group name="frame_17">
                <mesh
                  name="Object_250"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_250.geometry}
                  material={materials.Material_16}
                />
              </group>
            </group>
            <group name="Object_251" scale={0}>
              <group name="frame_16">
                <mesh
                  name="Object_253"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_253.geometry}
                  material={materials.Material_15}
                />
              </group>
            </group>
            <group name="Object_254" scale={0}>
              <group name="frame_15">
                <mesh
                  name="Object_256"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_256.geometry}
                  material={materials.Material_14}
                />
              </group>
            </group>
            <group name="Object_257" scale={0}>
              <group name="frame_14">
                <mesh
                  name="Object_259"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_259.geometry}
                  material={materials.Material_13}
                />
              </group>
            </group>
            <group name="Object_260" scale={0}>
              <group name="frame_13">
                <mesh
                  name="Object_262"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_262.geometry}
                  material={materials.Material_12}
                />
              </group>
            </group>
            <group name="Object_263" scale={0}>
              <group name="frame_12">
                <mesh
                  name="Object_265"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_265.geometry}
                  material={materials.Material_11}
                />
              </group>
            </group>
            <group name="Object_266" scale={0}>
              <group name="frame_11">
                <mesh
                  name="Object_268"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_268.geometry}
                  material={materials.Material_10}
                />
              </group>
            </group>
            <group name="Object_269" scale={0}>
              <group name="frame_10">
                <mesh
                  name="Object_271"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_271.geometry}
                  material={materials.Material_9}
                />
              </group>
            </group>
            <group name="Object_272" scale={0}>
              <group name="frame_9">
                <mesh
                  name="Object_274"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials.Material_8}
                />
              </group>
            </group>
            <group name="Object_275" scale={0}>
              <group name="frame_8">
                <mesh
                  name="Object_277"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_277.geometry}
                  material={materials.Material_7}
                />
              </group>
            </group>
            <group name="Object_278" scale={0}>
              <group name="frame_7">
                <mesh
                  name="Object_280"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials.Material_6}
                />
              </group>
            </group>
            <group name="Object_281" scale={0}>
              <group name="frame_6">
                <mesh
                  name="Object_283"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_283.geometry}
                  material={materials.Material_5}
                />
              </group>
            </group>
            <group name="Object_284" scale={0}>
              <group name="frame_5">
                <mesh
                  name="Object_286"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_286.geometry}
                  material={materials.Material_4}
                />
              </group>
            </group>
            <group name="Object_287" scale={0}>
              <group name="frame_4">
                <mesh
                  name="Object_289"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_289.geometry}
                  material={materials.Material_3}
                />
              </group>
            </group>
            <group name="Object_290" scale={0}>
              <group name="frame_3">
                <mesh
                  name="Object_292"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_292.geometry}
                  material={materials.Material_2}
                />
              </group>
            </group>
            <group name="Object_293" scale={0}>
              <group name="frame_2">
                <mesh
                  name="Object_295"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_295.geometry}
                  material={materials.Material_1}
                />
              </group>
            </group>
            <group name="Object_296" scale={0}>
              <group name="frame_1">
                <mesh
                  name="Object_298"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_298.geometry}
                  material={materials.Material_0}
                />
              </group>
            </group>
            <group name="Object_299">
              <group name="frame_0">
                <mesh
                  name="Object_301"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_301.geometry}
                  material={materials.Material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(CubeModel)

export default CubeLogo